/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MailmindRouteImport } from './routes/mailmind'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ModulesVoorraadRouteImport } from './routes/modules.voorraad'
import { Route as ModulesVerbeterpuntRouteImport } from './routes/modules.verbeterpunt'
import { Route as ModulesUitgifteRouteImport } from './routes/modules.uitgifte'
import { Route as ModulesToolsRouteImport } from './routes/modules.tools'
import { Route as ModulesScriptRouteImport } from './routes/modules.script'
import { Route as ModulesSchijfgebruikRouteImport } from './routes/modules.schijfgebruik'
import { Route as ModulesReflectieRouteImport } from './routes/modules.reflectie'
import { Route as ModulesPrinterRouteImport } from './routes/modules.printer'
import { Route as ModulesMedewerkerRouteImport } from './routes/modules.medewerker'
import { Route as ModulesKennisbankRouteImport } from './routes/modules.kennisbank'
import { Route as ModulesHardwareUitgavenRouteImport } from './routes/modules.hardware-uitgaven'
import { Route as ModulesDeviceRouteImport } from './routes/modules.device'
import { Route as ModulesCyberrisicoRouteImport } from './routes/modules.cyberrisico'
import { Route as ModulesBeheerRouteImport } from './routes/modules.beheer'
import { Route as ModulesAgendaRouteImport } from './routes/modules.agenda'
import { Route as ModulesAccountRouteImport } from './routes/modules.account'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'

const MailmindRoute = MailmindRouteImport.update({
  id: '/mailmind',
  path: '/mailmind',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesVoorraadRoute = ModulesVoorraadRouteImport.update({
  id: '/modules/voorraad',
  path: '/modules/voorraad',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesVerbeterpuntRoute = ModulesVerbeterpuntRouteImport.update({
  id: '/modules/verbeterpunt',
  path: '/modules/verbeterpunt',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesUitgifteRoute = ModulesUitgifteRouteImport.update({
  id: '/modules/uitgifte',
  path: '/modules/uitgifte',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesToolsRoute = ModulesToolsRouteImport.update({
  id: '/modules/tools',
  path: '/modules/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesScriptRoute = ModulesScriptRouteImport.update({
  id: '/modules/script',
  path: '/modules/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSchijfgebruikRoute = ModulesSchijfgebruikRouteImport.update({
  id: '/modules/schijfgebruik',
  path: '/modules/schijfgebruik',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesReflectieRoute = ModulesReflectieRouteImport.update({
  id: '/modules/reflectie',
  path: '/modules/reflectie',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesPrinterRoute = ModulesPrinterRouteImport.update({
  id: '/modules/printer',
  path: '/modules/printer',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesMedewerkerRoute = ModulesMedewerkerRouteImport.update({
  id: '/modules/medewerker',
  path: '/modules/medewerker',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesKennisbankRoute = ModulesKennisbankRouteImport.update({
  id: '/modules/kennisbank',
  path: '/modules/kennisbank',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesHardwareUitgavenRoute = ModulesHardwareUitgavenRouteImport.update({
  id: '/modules/hardware-uitgaven',
  path: '/modules/hardware-uitgaven',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesDeviceRoute = ModulesDeviceRouteImport.update({
  id: '/modules/device',
  path: '/modules/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesCyberrisicoRoute = ModulesCyberrisicoRouteImport.update({
  id: '/modules/cyberrisico',
  path: '/modules/cyberrisico',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesBeheerRoute = ModulesBeheerRouteImport.update({
  id: '/modules/beheer',
  path: '/modules/beheer',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesAgendaRoute = ModulesAgendaRouteImport.update({
  id: '/modules/agenda',
  path: '/modules/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesAccountRoute = ModulesAccountRouteImport.update({
  id: '/modules/account',
  path: '/modules/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/mailmind': typeof MailmindRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/account': typeof ModulesAccountRoute
  '/modules/agenda': typeof ModulesAgendaRoute
  '/modules/beheer': typeof ModulesBeheerRoute
  '/modules/cyberrisico': typeof ModulesCyberrisicoRoute
  '/modules/device': typeof ModulesDeviceRoute
  '/modules/hardware-uitgaven': typeof ModulesHardwareUitgavenRoute
  '/modules/kennisbank': typeof ModulesKennisbankRoute
  '/modules/medewerker': typeof ModulesMedewerkerRoute
  '/modules/printer': typeof ModulesPrinterRoute
  '/modules/reflectie': typeof ModulesReflectieRoute
  '/modules/schijfgebruik': typeof ModulesSchijfgebruikRoute
  '/modules/script': typeof ModulesScriptRoute
  '/modules/tools': typeof ModulesToolsRoute
  '/modules/uitgifte': typeof ModulesUitgifteRoute
  '/modules/verbeterpunt': typeof ModulesVerbeterpuntRoute
  '/modules/voorraad': typeof ModulesVoorraadRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/mailmind': typeof MailmindRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/account': typeof ModulesAccountRoute
  '/modules/agenda': typeof ModulesAgendaRoute
  '/modules/beheer': typeof ModulesBeheerRoute
  '/modules/cyberrisico': typeof ModulesCyberrisicoRoute
  '/modules/device': typeof ModulesDeviceRoute
  '/modules/hardware-uitgaven': typeof ModulesHardwareUitgavenRoute
  '/modules/kennisbank': typeof ModulesKennisbankRoute
  '/modules/medewerker': typeof ModulesMedewerkerRoute
  '/modules/printer': typeof ModulesPrinterRoute
  '/modules/reflectie': typeof ModulesReflectieRoute
  '/modules/schijfgebruik': typeof ModulesSchijfgebruikRoute
  '/modules/script': typeof ModulesScriptRoute
  '/modules/tools': typeof ModulesToolsRoute
  '/modules/uitgifte': typeof ModulesUitgifteRoute
  '/modules/verbeterpunt': typeof ModulesVerbeterpuntRoute
  '/modules/voorraad': typeof ModulesVoorraadRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/mailmind': typeof MailmindRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/account': typeof ModulesAccountRoute
  '/modules/agenda': typeof ModulesAgendaRoute
  '/modules/beheer': typeof ModulesBeheerRoute
  '/modules/cyberrisico': typeof ModulesCyberrisicoRoute
  '/modules/device': typeof ModulesDeviceRoute
  '/modules/hardware-uitgaven': typeof ModulesHardwareUitgavenRoute
  '/modules/kennisbank': typeof ModulesKennisbankRoute
  '/modules/medewerker': typeof ModulesMedewerkerRoute
  '/modules/printer': typeof ModulesPrinterRoute
  '/modules/reflectie': typeof ModulesReflectieRoute
  '/modules/schijfgebruik': typeof ModulesSchijfgebruikRoute
  '/modules/script': typeof ModulesScriptRoute
  '/modules/tools': typeof ModulesToolsRoute
  '/modules/uitgifte': typeof ModulesUitgifteRoute
  '/modules/verbeterpunt': typeof ModulesVerbeterpuntRoute
  '/modules/voorraad': typeof ModulesVoorraadRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/mailmind'
    | '/modules/$slug'
    | '/modules/account'
    | '/modules/agenda'
    | '/modules/beheer'
    | '/modules/cyberrisico'
    | '/modules/device'
    | '/modules/hardware-uitgaven'
    | '/modules/kennisbank'
    | '/modules/medewerker'
    | '/modules/printer'
    | '/modules/reflectie'
    | '/modules/schijfgebruik'
    | '/modules/script'
    | '/modules/tools'
    | '/modules/uitgifte'
    | '/modules/verbeterpunt'
    | '/modules/voorraad'
    | '/tickets/$id'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/mailmind'
    | '/modules/$slug'
    | '/modules/account'
    | '/modules/agenda'
    | '/modules/beheer'
    | '/modules/cyberrisico'
    | '/modules/device'
    | '/modules/hardware-uitgaven'
    | '/modules/kennisbank'
    | '/modules/medewerker'
    | '/modules/printer'
    | '/modules/reflectie'
    | '/modules/schijfgebruik'
    | '/modules/script'
    | '/modules/tools'
    | '/modules/uitgifte'
    | '/modules/verbeterpunt'
    | '/modules/voorraad'
    | '/tickets/$id'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/mailmind'
    | '/modules/$slug'
    | '/modules/account'
    | '/modules/agenda'
    | '/modules/beheer'
    | '/modules/cyberrisico'
    | '/modules/device'
    | '/modules/hardware-uitgaven'
    | '/modules/kennisbank'
    | '/modules/medewerker'
    | '/modules/printer'
    | '/modules/reflectie'
    | '/modules/schijfgebruik'
    | '/modules/script'
    | '/modules/tools'
    | '/modules/uitgifte'
    | '/modules/verbeterpunt'
    | '/modules/voorraad'
    | '/tickets/$id'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  MailmindRoute: typeof MailmindRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
  ModulesAccountRoute: typeof ModulesAccountRoute
  ModulesAgendaRoute: typeof ModulesAgendaRoute
  ModulesBeheerRoute: typeof ModulesBeheerRoute
  ModulesCyberrisicoRoute: typeof ModulesCyberrisicoRoute
  ModulesDeviceRoute: typeof ModulesDeviceRoute
  ModulesHardwareUitgavenRoute: typeof ModulesHardwareUitgavenRoute
  ModulesKennisbankRoute: typeof ModulesKennisbankRoute
  ModulesMedewerkerRoute: typeof ModulesMedewerkerRoute
  ModulesPrinterRoute: typeof ModulesPrinterRoute
  ModulesReflectieRoute: typeof ModulesReflectieRoute
  ModulesSchijfgebruikRoute: typeof ModulesSchijfgebruikRoute
  ModulesScriptRoute: typeof ModulesScriptRoute
  ModulesToolsRoute: typeof ModulesToolsRoute
  ModulesUitgifteRoute: typeof ModulesUitgifteRoute
  ModulesVerbeterpuntRoute: typeof ModulesVerbeterpuntRoute
  ModulesVoorraadRoute: typeof ModulesVoorraadRoute
  TicketsIdRoute: typeof TicketsIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mailmind': {
      id: '/mailmind'
      path: '/mailmind'
      fullPath: '/mailmind'
      preLoaderRoute: typeof MailmindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/voorraad': {
      id: '/modules/voorraad'
      path: '/modules/voorraad'
      fullPath: '/modules/voorraad'
      preLoaderRoute: typeof ModulesVoorraadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/verbeterpunt': {
      id: '/modules/verbeterpunt'
      path: '/modules/verbeterpunt'
      fullPath: '/modules/verbeterpunt'
      preLoaderRoute: typeof ModulesVerbeterpuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/uitgifte': {
      id: '/modules/uitgifte'
      path: '/modules/uitgifte'
      fullPath: '/modules/uitgifte'
      preLoaderRoute: typeof ModulesUitgifteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/tools': {
      id: '/modules/tools'
      path: '/modules/tools'
      fullPath: '/modules/tools'
      preLoaderRoute: typeof ModulesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/script': {
      id: '/modules/script'
      path: '/modules/script'
      fullPath: '/modules/script'
      preLoaderRoute: typeof ModulesScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/schijfgebruik': {
      id: '/modules/schijfgebruik'
      path: '/modules/schijfgebruik'
      fullPath: '/modules/schijfgebruik'
      preLoaderRoute: typeof ModulesSchijfgebruikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/reflectie': {
      id: '/modules/reflectie'
      path: '/modules/reflectie'
      fullPath: '/modules/reflectie'
      preLoaderRoute: typeof ModulesReflectieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/printer': {
      id: '/modules/printer'
      path: '/modules/printer'
      fullPath: '/modules/printer'
      preLoaderRoute: typeof ModulesPrinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/medewerker': {
      id: '/modules/medewerker'
      path: '/modules/medewerker'
      fullPath: '/modules/medewerker'
      preLoaderRoute: typeof ModulesMedewerkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/kennisbank': {
      id: '/modules/kennisbank'
      path: '/modules/kennisbank'
      fullPath: '/modules/kennisbank'
      preLoaderRoute: typeof ModulesKennisbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/hardware-uitgaven': {
      id: '/modules/hardware-uitgaven'
      path: '/modules/hardware-uitgaven'
      fullPath: '/modules/hardware-uitgaven'
      preLoaderRoute: typeof ModulesHardwareUitgavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/device': {
      id: '/modules/device'
      path: '/modules/device'
      fullPath: '/modules/device'
      preLoaderRoute: typeof ModulesDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/cyberrisico': {
      id: '/modules/cyberrisico'
      path: '/modules/cyberrisico'
      fullPath: '/modules/cyberrisico'
      preLoaderRoute: typeof ModulesCyberrisicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/beheer': {
      id: '/modules/beheer'
      path: '/modules/beheer'
      fullPath: '/modules/beheer'
      preLoaderRoute: typeof ModulesBeheerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/agenda': {
      id: '/modules/agenda'
      path: '/modules/agenda'
      fullPath: '/modules/agenda'
      preLoaderRoute: typeof ModulesAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/account': {
      id: '/modules/account'
      path: '/modules/account'
      fullPath: '/modules/account'
      preLoaderRoute: typeof ModulesAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  MailmindRoute: MailmindRoute,
  ModulesSlugRoute: ModulesSlugRoute,
  ModulesAccountRoute: ModulesAccountRoute,
  ModulesAgendaRoute: ModulesAgendaRoute,
  ModulesBeheerRoute: ModulesBeheerRoute,
  ModulesCyberrisicoRoute: ModulesCyberrisicoRoute,
  ModulesDeviceRoute: ModulesDeviceRoute,
  ModulesHardwareUitgavenRoute: ModulesHardwareUitgavenRoute,
  ModulesKennisbankRoute: ModulesKennisbankRoute,
  ModulesMedewerkerRoute: ModulesMedewerkerRoute,
  ModulesPrinterRoute: ModulesPrinterRoute,
  ModulesReflectieRoute: ModulesReflectieRoute,
  ModulesSchijfgebruikRoute: ModulesSchijfgebruikRoute,
  ModulesScriptRoute: ModulesScriptRoute,
  ModulesToolsRoute: ModulesToolsRoute,
  ModulesUitgifteRoute: ModulesUitgifteRoute,
  ModulesVerbeterpuntRoute: ModulesVerbeterpuntRoute,
  ModulesVoorraadRoute: ModulesVoorraadRoute,
  TicketsIdRoute: TicketsIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
